### ISSUE TITLE
Errore nel programma dopo aver selezionato "Serialize the selected files"

### ISSUE THREAD

**Issue by dadebert** [gekoxyz/eis-final#35]
Dopo aver scaricato articoli da theguardian, ho scelto "Serialize articles to xml file"

ho selezionato un articolo di nytimes e 2 di theguardian

ho selezionato "Serialize the selected files".

Dopodichè i file vengono serializzati, ma il programma dà errore stampando questo: (NON CRASHA, DA' SOLO ERRORE E SI PUO' CONTINUARE CON IL PROGRAMMA)

The selected files will be serialized:
- nytimes_articles_v2.csv
- theguardian_articles_20230609_172517_200.json
- theguardian_articles_20230609_172514_902.json
[INFO] - Scanned file .\assets\nytimes\nytimes_articles_v2.csv
[INFO] - XML file created successfully.
[INFO] - Added 1000 articles to the XML file
From which source do you want to select?
1. nytimes
2. theguardian
3. Serialize the selected files
4. Go back
Enter your choice: java.lang.ClassNotFoundException: it.unipd.dei.eis.adapters.TheGuardianJsonAdapter.java
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at it.unipd.dei.eis.InteractiveMenu.chooseAdapterAndSerialize(InteractiveMenu.java:158)
	at it.unipd.dei.eis.InteractiveMenu.serializerSubMenu(InteractiveMenu.java:96)
	at it.unipd.dei.eis.InteractiveMenu.runMenu(InteractiveMenu.java:35)
	at it.unipd.dei.eis.Main.main(Main.java:51)
java.lang.ClassNotFoundException: it.unipd.dei.eis.adapters.TheGuardianJsonAdapter.java
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at it.unipd.dei.eis.InteractiveMenu.chooseAdapterAndSerialize(InteractiveMenu.java:158)
	at it.unipd.dei.eis.InteractiveMenu.serializerSubMenu(InteractiveMenu.java:96)
	at it.unipd.dei.eis.InteractiveMenu.runMenu(InteractiveMenu.java:35)
	at it.unipd.dei.eis.Main.main(Main.java:51)

**Comment by dadebert** [comment]
ho notato che l'errore accade soltanto con gli articoli di theguardian

**Comment by dadebert** [comment]
![Immagine](https://github.com/gekoxyz/eis-final/assets/51121898/c917bf51-c8cf-4f90-8d37-9c68a6303f11)


il problema è la riga 94 di InteractiveMenu.java, non riesce a trovare la classe TheGuardianJSONAdapter
